
DATASET ACTIVATE DataSet1.
FREQUENCIES VARIABLES=Q2.5 Q9.1 Q9.3 Q9.4 Q9.7 Q9.2 Q9.8
  /HISTOGRAM NORMAL
  /ORDER=ANALYSIS.

* Hypothesis testing 1; Statistical tests

ONEWAY Q9.3 Q9.4 BY Q9.1
  /MISSING ANALYSIS
  /POSTHOC=TUKEY ALPHA(0.05).

REGRESSION
  /DEPENDENT Q9.3
  /METHOD=ENTER Q9.1 Q2.5 Q2.1 Q9.8.

*Hypothesis testing 2; Statistica tests


* ANOVA for focus during studying by exercise type.
ONEWAY Q9.4 BY Q9.2
  /MISSING ANALYSIS
   /POSTHOC=TUKEY ALPHA(0.05).

* Correlation analysis for selected variables.
CORRELATIONS 
  /VARIABLES=Q9.1 Q9.3 Q9.4 Q9.7 Q9.8
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.


CROSSTABS
  /TABLES=Q9.3 BY Q9.4
  /FORMAT=AVALUE TABLES
  /STATISTICS=CHISQ CORR
  /CELLS=COUNT
  /COUNT ROUND CELL.

DATASET ACTIVATE DataSet1.
DESCRIPTIVES VARIABLES=Q9.1
  /STATISTICS=MEAN STDDEV MIN MAX SEMEAN.



DESCRIPTIVES VARIABLES=Q9.4
  /STATISTICS=MEAN STDDEV MIN MAX SEMEAN.

FREQUENCIES VARIABLES=Q9.1
  /FORMAT=NOTABLE
  /STATISTICS=STDDEV MINIMUM MAXIMUM SEMEAN MEAN MEDIAN MODE
  /HISTOGRAM NORMAL
  /ORDER=ANALYSIS.


FREQUENCIES VARIABLES=Q9.4
  /FORMAT=NOTABLE
  /STATISTICS=STDDEV MINIMUM MAXIMUM SEMEAN MEAN MEDIAN MODE
  /HISTOGRAM NORMAL
  /ORDER=ANALYSIS.

* Chart Builder.
GGRAPH
  /GRAPHDATASET NAME="graphdataset" VARIABLES=Q9.1[name="Q9_1"] MEAN(Q9.3)[name="MEAN_Q9_3"] 
    MISSING=LISTWISE REPORTMISSING=NO
  /GRAPHSPEC SOURCE=INLINE.
BEGIN GPL
  SOURCE: s=userSource(id("graphdataset"))
  DATA: Q9_1=col(source(s), name("Q9_1"))
  DATA: MEAN_Q9_3=col(source(s), name("MEAN_Q9_3"))
  GUIDE: axis(dim(1), label("How often do you engage in physical exercise?"))
  GUIDE: axis(dim(2), label("Mean What is your current overall GPA?"))
  ELEMENT: interval(position(Q9_1*MEAN_Q9_3), shape.interior(shape.square))
END GPL.
