
DATASET ACTIVATE DataSet1.
CROSSTABS
  /TABLES=AgeGroup BY FieldofStudy
  /FORMAT=AVALUE TABLES
  /STATISTICS=CHISQ PHI 
  /CELLS=COUNT 
  /COUNT ROUND CELL.

GRAPH
  /BAR(GROUPED)=COUNT BY FieldofStudy BY AgeGroup
  /TITLE='Field of study by age group'.

CROSSTABS
  /TABLES=StateofMentalHealthAfterExams BY YearInUni
  /FORMAT=AVALUE TABLES
  /STATISTICS=CHISQ PHI 
  /CELLS=COUNT 
  /COUNT ROUND CELL
  /BARCHART.


CROSSTABS
  /TABLES= AnxietyPreExam BY Gender
  /FORMAT=AVALUE TABLES
  /STATISTICS=CHISQ PHI 
  /CELLS=COUNT 
  /COUNT ROUND CELL
  /BARCHART.

CROSSTABS
  /TABLES=FieldofStudy BY StressLevel
  /FORMAT=AVALUE TABLES
  /STATISTICS=CHISQ PHI 
  /CELLS=COUNT 
  /COUNT ROUND CELL
  /BARCHART.
