/* CHI SQUARE TEST
DATASET ACTIVATE DataSet1.
CROSSTABS
  /TABLES=diab BY smok
  /FORMAT=AVALUE TABLES
  /STATISTICS=CHISQ 
  /CELLS=COUNT EXPECTED 
  /COUNT ROUND CELL.

CROSSTABS
  /TABLES=diab BY stress
  /FORMAT=AVALUE TABLES
  /STATISTICS=CHISQ 
  /CELLS=COUNT EXPECTED 
  /COUNT ROUND CELL.



CROSSTABS
  /TABLES=diab BY sex
  /FORMAT=AVALUE TABLES
  /STATISTICS=CHISQ 
  /CELLS=COUNT EXPECTED 
  /COUNT ROUND CELL.

/* MANN WHITNEY TEST

NPAR TESTS
  /M-W= s1 BY diab(0 1)
  /MISSING ANALYSIS.



NPAR TESTS
  /M-W= chol1 BY diab(0 1)
  /MISSING ANALYSIS.



NPAR TESTS
  /M-W= bmi1 BY diab(0 1)
  /MISSING ANALYSIS.


/*Spearman's Rank-Order Correlation

NONPAR CORR
  /VARIABLES=bmi1 chol1
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.


NONPAR CORR
  /VARIABLES=s1 d1
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.



NONPAR CORR
  /VARIABLES=h1 w1
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.


/*LOGISTIC REGRESSION


LOGISTIC REGRESSION VARIABLES diab
  /METHOD=ENTER age sex s1 d1 h1 w1 bmi1 chol1 smok dr fats salt phys stress 
  /CONTRAST (sex)=Indicator
  /CONTRAST (smok)=Indicator
  /CONTRAST (dr)=Indicator
  /CONTRAST (fats)=Indicator
  /CONTRAST (salt)=Indicator
  /CONTRAST (phys)=Indicator
  /CONTRAST (stress)=Indicator
  /CRITERIA=PIN(.05) POUT(.10) ITERATE(20) CUT(.5).


LOGISTIC REGRESSION VARIABLES diab
  /METHOD=ENTER age sex s1 d1 h1 w1 bmi1 chol1 smok dr fats salt phys stress 
  /CRITERIA=PIN(.05) POUT(.10) ITERATE(20) CUT(.5).

/*KRUSKAL WALLIS TEST

NPAR TESTS
  /K-W=stress BY phys(0 2)
  /MISSING ANALYSIS.

NPAR TESTS
  /K-W=diab BY smok(0 2)
  /MISSING ANALYSIS.

NPAR TESTS
  /K-W=diab BY salt(0 2)
  /MISSING ANALYSIS.

NPAR TESTS
  /K-W=diab BY fats(0 2)
  /MISSING ANALYSIS.

