DATASET ACTIVATE DataSet1.
GRAPH
  /BAR(SIMPLE)=VALUE(Population) BY Age.


DATASET ACTIVATE DataSet3.
GRAPH
  /BAR(SIMPLE)=VALUE(Population) BY Race.



DATASET ACTIVATE DataSet4.
GRAPH
  /BAR(SIMPLE)=VALUE(Population) BY Gender.
